### ISSUE TITLE
Nav button does not get removed when shutting down plugin

### ISSUE THREAD

**Issue by YvesW** [capslock13/AdvancedRaidTracker#2]
https://github.com/capslock13/AdvancedRaidTracker/assets/7929021/9df4687c-1e0a-487c-983e-d408ee9ee427

```2024-05-24 01:58:54 CEST [AWT-EventQueue-0] WARN  n.r.c.plugins.config.PluginListPanel - Error when stopping plugin AdvancedRaidTrackerPlugin
net.runelite.client.plugins.PluginInstantiationException: java.lang.NullPointerException
	at net.runelite.client.plugins.PluginManager.stopPlugin(PluginManager.java:488)
	at net.runelite.client.plugins.config.PluginListPanel.stopPlugin(PluginListPanel.java:318)
	at net.runelite.client.plugins.config.PluginListItem.lambda$new$4(PluginListItem.java:175)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at com.advancedraidtracker.AdvancedRaidTrackerPlugin.shutDown(AdvancedRaidTrackerPlugin.java:144)
	at net.runelite.client.plugins.PluginManager.stopPlugin(PluginManager.java:481)
	... 38 common frames omitted
2024-05-24 01:58:55 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:58:55 CEST [AWT-EventQueue-0] WARN  n.r.c.plugins.config.PluginListPanel - Error when stopping plugin AdvancedRaidTrackerPlugin
net.runelite.client.plugins.PluginInstantiationException: java.lang.NullPointerException
	at net.runelite.client.plugins.PluginManager.stopPlugin(PluginManager.java:488)
	at net.runelite.client.plugins.config.PluginListPanel.stopPlugin(PluginListPanel.java:318)
	at net.runelite.client.plugins.config.PluginListItem.lambda$new$4(PluginListItem.java:175)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.NullPointerException: null
	at com.advancedraidtracker.AdvancedRaidTrackerPlugin.shutDown(AdvancedRaidTrackerPlugin.java:144)
	at net.runelite.client.plugins.PluginManager.stopPlugin(PluginManager.java:481)
	... 38 common frames omitted
2024-05-24 01:58:55 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:58:56 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:58:57 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:58:57 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:58:58 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:58:58 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:58:59 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:00 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:00 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:01 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:01 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:02 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:03 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:03 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:04 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:04 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:05 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:06 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:06 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:07 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:07 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:08 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:09 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:09 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:10 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:10 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:11 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:12 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:12 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:13 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:13 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:14 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:15 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:15 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:16 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:16 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:17 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:18 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:18 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:19 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:19 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:20 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:21 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:21 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:22 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:22 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:23 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:24 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:24 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:25 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:25 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:26 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:27 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:27 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:28 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:28 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:29 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:30 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:30 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:31 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:31 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:32 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:33 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:33 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:34 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:34 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:35 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:36 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:36 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:37 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:37 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:38 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:39 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:39 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:40 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:40 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:41 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:42 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:42 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:43 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:43 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:44 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:45 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:45 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:46 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:46 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:47 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:48 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:48 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:49 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:49 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:50 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:51 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:51 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:52 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:52 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:53 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:54 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:54 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:55 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:55 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:56 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:57 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:57 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:58 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:58 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 01:59:59 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:00 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:00 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:01 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:01 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:02 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:03 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:03 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:04 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:04 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:05 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:06 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:06 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:07 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:07 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:08 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:09 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:09 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:10 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:10 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:11 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:12 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:12 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:13 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:13 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:14 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:15 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:15 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:16 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:16 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:17 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:18 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:18 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:19 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:19 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:20 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:21 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:21 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:22 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:22 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:23 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:24 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:24 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:25 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:25 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:26 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:27 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:27 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:28 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:28 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:29 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:30 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:30 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:31 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:31 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:32 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:33 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:33 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:34 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:34 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:35 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:36 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:36 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:37 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:37 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:38 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:39 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log
2024-05-24 02:00:39 CEST [Client] INFO  c.a.utility.datautility.DataWriter - Failed clearing buffered tob data to log```

**Comment by capslock13** [comment]
This has been fixed with f59de0a
